/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as NewsRouteImport } from './routes/news'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as NewsNewsIdRouteImport } from './routes/news.$newsId'
import { Route as FacultyFacultyIdRouteImport } from './routes/faculty.$facultyId'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsNewsIdRoute = NewsNewsIdRouteImport.update({
  id: '/$newsId',
  path: '/$newsId',
  getParentRoute: () => NewsRoute,
} as any)
const FacultyFacultyIdRoute = FacultyFacultyIdRouteImport.update({
  id: '/faculty/$facultyId',
  path: '/faculty/$facultyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRouteWithChildren
  '/team': typeof TeamRoute
  '/faculty/$facultyId': typeof FacultyFacultyIdRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gallery': typeof GalleryRoute
  '/team': typeof TeamRoute
  '/faculty/$facultyId': typeof FacultyFacultyIdRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/news': typeof NewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRouteWithChildren
  '/team': typeof TeamRoute
  '/faculty/$facultyId': typeof FacultyFacultyIdRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/gallery'
    | '/news'
    | '/team'
    | '/faculty/$facultyId'
    | '/news/$newsId'
    | '/projects/$projectId'
    | '/news/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/gallery'
    | '/team'
    | '/faculty/$facultyId'
    | '/news/$newsId'
    | '/projects/$projectId'
    | '/news'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/gallery'
    | '/news'
    | '/team'
    | '/faculty/$facultyId'
    | '/news/$newsId'
    | '/projects/$projectId'
    | '/news/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GalleryRoute: typeof GalleryRoute
  NewsRoute: typeof NewsRouteWithChildren
  TeamRoute: typeof TeamRoute
  FacultyFacultyIdRoute: typeof FacultyFacultyIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof NewsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$newsId': {
      id: '/news/$newsId'
      path: '/$newsId'
      fullPath: '/news/$newsId'
      preLoaderRoute: typeof NewsNewsIdRouteImport
      parentRoute: typeof NewsRoute
    }
    '/faculty/$facultyId': {
      id: '/faculty/$facultyId'
      path: '/faculty/$facultyId'
      fullPath: '/faculty/$facultyId'
      preLoaderRoute: typeof FacultyFacultyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NewsRouteChildren {
  NewsNewsIdRoute: typeof NewsNewsIdRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsNewsIdRoute: NewsNewsIdRoute,
  NewsIndexRoute: NewsIndexRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GalleryRoute: GalleryRoute,
  NewsRoute: NewsRouteWithChildren,
  TeamRoute: TeamRoute,
  FacultyFacultyIdRoute: FacultyFacultyIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
