/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnershipRouteImport } from './routes/partnership'
import { Route as NewsRouteImport } from './routes/news'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as AssistantsRouteImport } from './routes/assistants'
import { Route as AreaRouteImport } from './routes/area'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as FacultyIndexRouteImport } from './routes/faculty.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as NewsNewsIdRouteImport } from './routes/news.$newsId'
import { Route as FacultyFacultyIdRouteImport } from './routes/faculty.$facultyId'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipRoute = PartnershipRouteImport.update({
  id: '/partnership',
  path: '/partnership',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantsRoute = AssistantsRouteImport.update({
  id: '/assistants',
  path: '/assistants',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaRoute = AreaRouteImport.update({
  id: '/area',
  path: '/area',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsRoute,
} as any)
const FacultyIndexRoute = FacultyIndexRouteImport.update({
  id: '/faculty/',
  path: '/faculty/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsNewsIdRoute = NewsNewsIdRouteImport.update({
  id: '/$newsId',
  path: '/$newsId',
  getParentRoute: () => NewsRoute,
} as any)
const FacultyFacultyIdRoute = FacultyFacultyIdRouteImport.update({
  id: '/faculty/$facultyId',
  path: '/faculty/$facultyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/area': typeof AreaRoute
  '/assistants': typeof AssistantsRoute
  '/awards': typeof AwardsRoute
  '/equipment': typeof EquipmentRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRouteWithChildren
  '/partnership': typeof PartnershipRoute
  '/privacy': typeof PrivacyRoute
  '/faculty/$facultyId': typeof FacultyFacultyIdRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/faculty/': typeof FacultyIndexRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/area': typeof AreaRoute
  '/assistants': typeof AssistantsRoute
  '/awards': typeof AwardsRoute
  '/equipment': typeof EquipmentRoute
  '/gallery': typeof GalleryRoute
  '/partnership': typeof PartnershipRoute
  '/privacy': typeof PrivacyRoute
  '/faculty/$facultyId': typeof FacultyFacultyIdRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/faculty': typeof FacultyIndexRoute
  '/news': typeof NewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/area': typeof AreaRoute
  '/assistants': typeof AssistantsRoute
  '/awards': typeof AwardsRoute
  '/equipment': typeof EquipmentRoute
  '/gallery': typeof GalleryRoute
  '/news': typeof NewsRouteWithChildren
  '/partnership': typeof PartnershipRoute
  '/privacy': typeof PrivacyRoute
  '/faculty/$facultyId': typeof FacultyFacultyIdRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/faculty/': typeof FacultyIndexRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/area'
    | '/assistants'
    | '/awards'
    | '/equipment'
    | '/gallery'
    | '/news'
    | '/partnership'
    | '/privacy'
    | '/faculty/$facultyId'
    | '/news/$newsId'
    | '/projects/$projectId'
    | '/faculty/'
    | '/news/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/area'
    | '/assistants'
    | '/awards'
    | '/equipment'
    | '/gallery'
    | '/partnership'
    | '/privacy'
    | '/faculty/$facultyId'
    | '/news/$newsId'
    | '/projects/$projectId'
    | '/faculty'
    | '/news'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/area'
    | '/assistants'
    | '/awards'
    | '/equipment'
    | '/gallery'
    | '/news'
    | '/partnership'
    | '/privacy'
    | '/faculty/$facultyId'
    | '/news/$newsId'
    | '/projects/$projectId'
    | '/faculty/'
    | '/news/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AreaRoute: typeof AreaRoute
  AssistantsRoute: typeof AssistantsRoute
  AwardsRoute: typeof AwardsRoute
  EquipmentRoute: typeof EquipmentRoute
  GalleryRoute: typeof GalleryRoute
  NewsRoute: typeof NewsRouteWithChildren
  PartnershipRoute: typeof PartnershipRoute
  PrivacyRoute: typeof PrivacyRoute
  FacultyFacultyIdRoute: typeof FacultyFacultyIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  FacultyIndexRoute: typeof FacultyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnership': {
      id: '/partnership'
      path: '/partnership'
      fullPath: '/partnership'
      preLoaderRoute: typeof PartnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistants': {
      id: '/assistants'
      path: '/assistants'
      fullPath: '/assistants'
      preLoaderRoute: typeof AssistantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area': {
      id: '/area'
      path: '/area'
      fullPath: '/area'
      preLoaderRoute: typeof AreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof NewsRoute
    }
    '/faculty/': {
      id: '/faculty/'
      path: '/faculty'
      fullPath: '/faculty/'
      preLoaderRoute: typeof FacultyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$newsId': {
      id: '/news/$newsId'
      path: '/$newsId'
      fullPath: '/news/$newsId'
      preLoaderRoute: typeof NewsNewsIdRouteImport
      parentRoute: typeof NewsRoute
    }
    '/faculty/$facultyId': {
      id: '/faculty/$facultyId'
      path: '/faculty/$facultyId'
      fullPath: '/faculty/$facultyId'
      preLoaderRoute: typeof FacultyFacultyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NewsRouteChildren {
  NewsNewsIdRoute: typeof NewsNewsIdRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsNewsIdRoute: NewsNewsIdRoute,
  NewsIndexRoute: NewsIndexRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AreaRoute: AreaRoute,
  AssistantsRoute: AssistantsRoute,
  AwardsRoute: AwardsRoute,
  EquipmentRoute: EquipmentRoute,
  GalleryRoute: GalleryRoute,
  NewsRoute: NewsRouteWithChildren,
  PartnershipRoute: PartnershipRoute,
  PrivacyRoute: PrivacyRoute,
  FacultyFacultyIdRoute: FacultyFacultyIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  FacultyIndexRoute: FacultyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
